name: state_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 1.2.6
  provider: 4.3.3
  flutter_bloc: 6.1.3
  uuid: 2.2.2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 7.1.0


flutter:
  uses-material-design: true