name: a2_paipai_shopping_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 1.2.6
  provider: 4.3.3
  flutter_bloc: 6.1.3
  uuid: 2.2.2
  cupertino_icons: ^1.0.2
  flutter_cache_manager: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: 1.2.6
  provider: 4.3.3
  flutter_bloc: 6.1.3
  uuid: 2.2.2
  flutter_cache_manager: 2.1.2

flutter:
  uses-material-design: true
  assets:
    - images/
